version: "3"
services:
  client_old:
    env_file:
      - .env
    build: node
    image: client_old:latest
    ports:
      - "3001:3001"
    working_dir: /data
    command: exit
    volumes:
      - ../client_old:/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  client:
    env_file:
      - .env
    build: node
    image: client:latest
    ports:
      - "8080:8080"
    working_dir: /data
    command: npm run devserver
    volumes:
      - ../client:/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  mongodb:
    image: mongo:4.2
    volumes:
     - mongo:/data/db
  server:
    env_file:
      - .env
    build: node
    image: server:latest
    ports:
      - "3000:3000"
      - "9229:9229"
    working_dir: /data
    command: npm run server
    volumes:
      - ../server:/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
volumes:
  mongo:
